### ISSUE TITLE
IndexedAccessType (keyor typeof)

### ISSUE THREAD

**Issue by karlismelderis** [lukeautry/tsoa#1019]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

I did found similar closed issue:
https://github.com/lukeautry/tsoa/issues/862
and PR:
https://github.com/lukeautry/tsoa/pull/636

## Expected Behavior

I expect such API schema to be generated:
```yaml
                arrayValue:
                    items:
                        type: string
                        enum:
                            - PUBLIC
                            - REMOTE
                            - NONE
                    type: array
                    nullable: true
```

```ts
enum Values {
PUBLIC: 'some public text',
REMOTE: 'some remote text',
NONE: 'some none text'
}

interface Example {
  arrayValue: typeof Values[keyof typeof Values][] | null;
}
```

or with merged ENUMs:
```ts
enum ValuesA {
PUBLIC: 'some public text',
REMOTE: 'some remote text'
}
enum ValuesB {
NONE: 'some none text'
}

const Values {
...ValuesA,
...ValuesB
}

interface Example {
  arrayValue: typeof Values[keyof typeof Values][] | null;
}
```

## Current Behavior

TSOA fails to generate spec and fails with error:
```
Generate routes error.
 Error: Unknown type: IndexedAccessType

This was caused by 'typeof Value[keyof typeof Value][]'
```

## Possible Solution

I did try to add code lines mentioned in issue (https://github.com/lukeautry/tsoa/issues/862) and API spec got generated as expected.

## Context (Environment)

Version of the library: 3.8.0
Version of NodeJS: 14.16.0

- Confirm you were using yarn not npm: [x]
