### ISSUE TITLE
Can't customize path parameter format

### ISSUE THREAD

**Issue by kvet** [lukeautry/tsoa#1022]
## Can't customize path parameter using `@format`

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
paths:
    '/test/{testId}':
        get:
            parameters:
                -
                    in: path
                    name: testId
                    required: true
                    schema:
                        format: int64
                        type: integer
```

## Current Behavior

```yaml
paths:
    '/test/{testId}':
        get:
            parameters:
                -
                    in: path
                    name: testId
                    required: true
                    schema:
                        format: int32
                        type: integer
```

## Steps to reproduce

```ts
@Route('test')
export class TestController extends Controller {
  /**
   * @isInt testId
   * @format testId int64
   */
  @Get('{testId}')
  public async getSink(@Path() testId: number): Promise<Test> {
    // @ts-ignore
    return undefined;
  }
}
```

## Context (Environment)

Version of the library: 3.8.0
Version of NodeJS: 16.2.0

- Confirm you were using yarn not npm: yarn

## Detailed Description

`@format` keyword is not working with json path parameters
