### ISSUE TITLE
Generic parameter as object key

### ISSUE THREAD

**Issue by karlismelderis** [lukeautry/tsoa#1030]
I'm trying to create reusable generic HAL interface but seems that TSOA doesn't detect key values passed to generic type

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
        HalCollection_attachments.Attachment_:
            properties:
                _embedded:
                    properties:
                        attachments:
                        type: array
                            ...type items
                    type: object

```

```ts
interface HalCollection<K extends string, T> {
  _embedded: {
    [key in K]: T[];
  };
}

public async getAttachments(): Promise<HalCollection<'attachments', Attachment>> {
//return collection
}

```

## Current Behavior

```yaml
        HalCollection_attachments.Attachment_:
            properties:
                _embedded:
                    properties: {} <- missing items as such
                    type: object
            required:
                - _embedded
            type: object
            additionalProperties: false
```

## Possible Solution

Had to repeat HAL structure to get proper API spec which is not great if you have dozenths of endpoints 

```ts
public async getAttachments(): Promise<{
    _embedded: {
      attachments: Attachment[];
    };
}> {
    //return collection
}
```

## Context (Environment)

Version of the library: 3.8.0
Version of NodeJS: 14/16

- Confirm you were using yarn not npm: [x]
