### ISSUE TITLE
IsType Annotation Support

### ISSUE THREAD

**Issue by DjakaTechnology** [lukeautry/tsoa#1091]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
            intAnnotated:
                type: integer
                format: int32
            longAnnotated:
                type: integer
                format: int64
            doubleAnnotated:
                type: number
                format: double
            floatAnnotated:
                type: number
                format: float
```

```ts
  @IsInt()
  public intAnnotated: number;
  @IsLong()
  public longAnnotated: number;
  @IsDouble()
  public doubleAnnotated: number;
  @IsFloat()
  public floatAnnotated: number;
```

## Current Behavior

`@IsType` annotation is not possible

## Possible Solution

Add `@IsType` support outside of java doc

## Context (Environment)

Version of the library: v3.11.2

- Confirm you were using yarn not npm: [x]

## Detailed Description

Writing java docs is not typesafe and quite overkill if only used for defining int, long etc. By giving annotation option, we can write less code and reduce potential typo since it will be validated by typescript

## Breaking change?
No
