### ISSUE TITLE
Allow `@Example` using TypeScript's Decorator

### ISSUE THREAD

**Issue by DjakaTechnology** [lukeautry/tsoa#1094]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
User:
            properties:
                name:
                    type: string
                    description: 'This is description'
                    example: 'John Doe'
                nameDecoration:
                    type: string
                    example: 'John Doe'
            required:
                - name
                - nameDecoration
            type: object
            additionalProperties: false
```

```ts
export class User {

  /**
  * This is description
  * 
  * @example "John Doe"
  * */
  name: string

  @Example("John Doe")
  nameDecoration: string
}
```

## Current Behavior
```yaml
User:
            properties:
                name:
                    type: string
                    description: 'This is description'
                    example: 'John Doe'
                nameDecoration:
                    type: string
                    example: 'John Doe'
            required:
                - name
                - nameDecoration
            type: object
            additionalProperties: false
```

## Possible Solution

Allow decorator to be used for `@Example` not just JSDoc

## Context (Environment)

Version of the library: v3.11.2

- Confirm you were using yarn not npm: [x]

## Detailed Description
Similar with `@Extension` and lack of `@Is{Type}`, the `@Example` is not processed when using decorator,  only JSDoc comments are processed. I prefer using decorator and I think expanding this to decorator doesn't have any harm (aside from extra overhead) but it gives user's flexibility to choose which style they prefer.

## Breaking change?
No
