### ISSUE TITLE
Unable to use negative value in Example decorator

### ISSUE THREAD

**Issue by madf12** [lukeautry/tsoa#1133]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Numeric properties should be able to be negative.

```yaml
"examples": {
  "Example 1": {
    "value": {
      "email": "test@email.com",
      "name": "First Last",
      "location": {
        "latitude": 53.893009,
        "longitude": 27.567444
      },
      "savedLocations": [
        {
          "latitude": 12,
          "longitude": 21
        },
        {
          "latitude": 33,
          "longitude": -33
        }
      ]
    }
  }
}
```

## Current Behavior

Properties with negative values aren't included in generated `swagger.json` file.

```yaml
"examples": {
  "Example 1": {
    "value": {
      "email": "test@email.com",
      "name": "First Last",
      "location": {
        "latitude": 53.893009,
        "longitude": 27.567444
      },
      "savedLocations": [
        {
          "latitude": 12,
          "longitude": 21
        },
        {
          "latitude": 33
        }
      ]
    }
  }
}
```

## Steps to Reproduce

1. Use following Example decorator:
```ts
@Example<IUserProfile>({
    email: 'test@email.com',
    name: 'First Last',
    location: {
      latitude: 53.893009,
      longitude: 27.567444,
    },
    savedLocations: [
      {
        latitude: 12,
        longitude: 21,
      },
      {
        latitude: 33,
        longitude: -33,
      },
    ],
  })
```
2. As type was used this interface:
```ts
interface IUserProfile {
  name?: string;
  email?: string;
  location?: Coordinates;
  savedLocations?: Array<Coordinates>;
}
```
3. Run `yarn tsoa swagger`
4. ???
5. Profit

## Context (Environment)

Version of the library: 3.14.0
Version of NodeJS: 14.17.0

- Confirm you were using yarn not npm: [x]
