### ISSUE TITLE
Add example labels to parameters

### ISSUE THREAD

**Issue by thetrevdev** [lukeautry/tsoa#1232]
## Adds labels to examples for parameters.  Keeps the existing behavior if no labels provided

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
paths:
  /somepath:
    post:
      ...
      body:
        content:
          application/json:
            examples:
              NamedExample:
                value:
                  a: b
```

## Current Behavior

```yaml
paths:
  /somepath:
    post:
      ...
      body:
        content:
          application/json:
            examples:
              Example 1:
                value:
                  a: b

```

## Possible Solution

The @Example decorator for responses supports labels but wasn't used on parameter examples

## Steps to Reproduce

```
  /**
   * @example body.NamedExample {
   * "a" : "b"
   * }
  */ 
```

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: 14/16
- [x] Confirm you were using yarn not npm: 

## Detailed Description

Example labels are already parsed but weren't added to the parameter object.  PR coming shortly

## Breaking change

No
