### ISSUE TITLE
How to return integer from method call

### ISSUE THREAD

**Issue by szekelyisz** [lukeautry/tsoa#1285]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I want a controller method to return an int32. I didn't find any documented way to do this. JSDoc annotation `/** @isInt */` works for parameters and number fields of structures, but not for response bodies (or at least it's not documented).

```yaml
"responses": {
	"200": {
		"description": "Ok",
		"content": {
			"application/json": {
				"schema": {
					"type": "integer",
					"format": "int32"
				}
			}
		}
}
```

How do you achieve this?

## Context (Environment)

Version of the library: 4.1.1
Version of NodeJS: 12.22.12

- Confirm you were using yarn not npm: [X]

**Comment by szekelyisz** [comment]
Found a hacky workaround.

```typescript
import { Controller, Get, Route } from "tsoa";

/**
 * @isInt
 */
type Integer = number;

@Route("/")
export class MyController extends Controller {
  @Get("/")
  public async get(): Promise<Integer> {
    return Promise.resolve(1);
  }
}
```

which generates

```yaml
  "components": {
    "schemas": {
      "Integer": {
        "type": "integer",
        "format": "int32"
      },
    }
  }

  "paths": {
    "/": {
      "get": {
        "operationId": "Get",
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Integer"
                }
              }
            }
          }
        },
        "security": [],
        "parameters": []
      }
    }
  }
```
