### ISSUE TITLE
"." in method docs example will break rendering

### ISSUE THREAD

**Issue by pquerner** [lukeautry/tsoa#1286]
I have a endpoint which consumes a JSON body with a optional `callback_url` property, which is of type string. If this property is set, we will `HTTP POST` to this URL. 

Setting up examples with

```
    /**
    * Get status for order id
    *
    * @param orderId
    * @isString orderId
    * @param body Accepts external callback url<br>
    * which will receive the response from our API as POST request<br><br>
    * Currently only accessible URLs are tested. If your URL needs authentication, please contact us.
    * @example body {
    *  "session": "example",
    *  "callback_url": "https:\/\/external.url.com\/api\/post\/stuff\/here"
    * }
    * @example body {
    *  "session": "example"
    * }
    */
```

I have also tried the URL string unescaped, or without slashes (except for the protocol).
A string such as `a` will render it just fine, so I suspect something with the URL string itself, although I am not sure which part is responsible (protocol, slash escapes, ...)

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

`Example 1` should be displayed / generated without problems.

## Current Behavior

Example is generated as
![image](https://user-images.githubusercontent.com/4364044/179926192-514a622d-f754-4a46-a0c9-692010eed875.png)

while missing the header `Example 1` and the actual example. When changing the selectbox option to any other type, and back to the `Example 1` (empty string), this is shown:

![image](https://user-images.githubusercontent.com/4364044/179926448-3ddd962c-6146-4191-8dc0-9bd527637604.png)

Using a string for `callback_url` such as `a` will output this:

![image](https://user-images.githubusercontent.com/4364044/179929288-6c79d0bd-efda-44a3-80a5-042d987aa7e3.png)

Code:

```
    * @example body {
    *  "session": "example",
    *  "callback_url": "a"
    * }
```

## Context (Environment)

Version of the library: 4.1.0
Version of NodeJS: v18.6.0

Swagger yml generated:

```yaml
{
	"components": {
		"examples": {},
		"headers": {},
		"parameters": {},
		"requestBodies": {},
		"responses": {},
		"schemas": {
			"RequestError": {
				"properties": {
					"success": {
						"type": "boolean",
						"enum": [
							false
						],
						"nullable": false
					},
					"error": {
						"type": "number",
						"enum": [
							500
						],
						"nullable": false
					},
					"details": {
						"properties": {},
						"additionalProperties": {
							"properties": {
								"value": {
									"type": "string"
								},
								"message": {
									"type": "string"
								}
							},
							"type": "object"
						},
						"type": "object"
					}
				},
				"required": [
					"success",
					"error"
				],
				"type": "object",
				"additionalProperties": false
			},
			"UnauthorizedError": {
				"properties": {
					"success": {
						"type": "boolean",
						"enum": [
							false
						],
						"nullable": false
					},
					"error": {
						"type": "number",
						"enum": [
							401
						],
						"nullable": false
					}
				},
				"required": [
					"success",
					"error"
				],
				"type": "object",
				"additionalProperties": false
			},
			"InternalError": {
				"properties": {
					"success": {
						"type": "boolean",
						"enum": [
							false
						],
						"nullable": false
					},
					"error": {
						"type": "number",
						"enum": [
							500
						],
						"nullable": false
					}
				},
				"required": [
					"success",
					"error"
				],
				"type": "object",
				"additionalProperties": false
			},
			"StatusGetRequest": {
				"properties": {
					"session": {
						"type": "string"
					},
					"callback_url": {
						"type": "string"
					}
				},
				"required": [
					"session"
				],
				"type": "object",
				"additionalProperties": false
			}
		},
		"securitySchemes": {
			"api_key": {
				"type": "apiKey",
				"name": "x-api-key",
				"in": "header"
			}
		}
	},
	"info": {
		"title": "xxx",
		"version": "1.0.0",
		"contact": {
			"name": "xx ",
			"url": "xxx"
		}
	},
	"openapi": "3.0.0",
	"paths": {
		"/status/get/order/{orderId}": {
			"post": {
				"operationId": "GetStatusForOrder",
				"responses": {
					"200": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {}
							}
						}
					},
					"400": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/RequestError"
								}
							}
						}
					},
					"401": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/UnauthorizedError"
								}
							}
						}
					},
					"500": {
						"description": "",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/InternalError"
								}
							}
						}
					}
				},
				"description": "Get status for order id",
				"security": [
					{
						"api_key": []
					}
				],
				"parameters": [
					{
						"in": "path",
						"name": "orderId",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"description": "Accepts external callback url<br>\nwhich will receive the response from our API as POST request<br><br>\nCurrently only accessible URLs are tested. If your URL needs authentication, please contact us.",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/StatusGetRequest",
								"description": "Accepts external callback url<br>\nwhich will receive the response from our API as POST request<br><br>\nCurrently only accessible URLs are tested. If your URL needs authentication, please contact us."
							},
							"examples": {
								"": {
									"value": {
										"session": "example",
										"callback_url": "https://external.url.com/api/post/stuff/here"
									}
								},
								"Example 1": {
									"value": {
										"session": "example"
									}
								}
							}
						}
					}
				}
			}
		}
	},
	"servers": [
		{
			"url": "/"
		}
	]
}
```

This part of the example is empty string:

```yaml
"examples": {
								"": {
									"value": {
										"session": "example",
										"callback_url": "https://external.url.com/api/post/stuff/here"
									}
								},
								"Example 1": {
									"value": {
										"session": "example"
									}
								}
							}
```
