### ISSUE TITLE
GenerateMetadataError: JSON format is incorrect: Unexpected token 's'

### ISSUE THREAD

**Issue by nkcoder** [lukeautry/tsoa#1359]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

**tsoa** should parse `@Post` annotation with `@Path`.

## Current Behavior

When I run `tsoa spec`, I got the following error:

```
> tsoa spec

Generate swagger error.
 GenerateMetadataError: JSON format is incorrect: Unexpected token 's', " some-encry"... is not valid JSON
 in 'PurchaseController.purchase'
```

`tsoa.json`:
```yaml
{
  "entryFile": "src/index.ts",
  "noImplicitAdditionalProperties": "throw-on-extras",
  "spec": {
    "outputDirectory": "docs/api",
    "specVersion": 3,
    "yaml": true
  }
}
```

```ts
@Route('v1/listings')
export class PurchaseController {
  @SuccessResponse('200')
  @Post(':listingId/purchase')
  public static async purchase(@Path() listingId: string, @Body() purchaseRequest: PurchaseRequest): Promise<void> {
  // ...
  }
}
```

## Context (Environment)

Version of the library: "tsoa": "^4.1.3",
Version of NodeJS: v19.3.0

- Confirm you were using yarn not npm: **I'm using npm**

## Detailed Description

I checked the example [PostControlloer](https://github.com/lukeautry/tsoa/blob/master/tests/fixtures/controllers/postController.ts) here, and I tried to change the `@Post` annotation to:
```
@Post('{listingId}/purchase')
```
Still got the same error: `GenerateMetadataError: JSON format is incorrect: Unexpected token 's', " some-encry"... is not valid JSON`. Just not sure what the error means.
