### ISSUE TITLE
Nullable attribute missing when type dereferenced from array type

### ISSUE THREAD

**Issue by Danoha** [lukeautry/tsoa#1395]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

Hi. We found a bug in the type resolver. It manifests as a missing nullable attribute of an object property when the object type is dereferenced from an array type. I will try to submit a PR if I find the time.

## Expected Behavior

```ts
type Model = {
  items: {
    createdAt?: Date|null;
  }[];
}

type TestResult = {
    test: Model["items"][number];
}
```

```yaml
        TestResult:
            properties:
                test:
                    properties:
                        createdAt:
                            type: string
                            format: date-time
                            nullable: true
                    type: object
            required:
                - test
            type: object
```

## Current Behavior

```yaml
        TestResult:
            properties:
                test:
                    properties:
                        createdAt:
                            type: string
                            format: date-time
                    type: object
            required:
                - test
            type: object
```

## Steps to Reproduce

Repro repo: https://github.com/Danoha/tsoa-repro/tree/main

- npm i
- npx tsoa spec

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 19.2.0
