### ISSUE TITLE
Parameter examples are incorrectly made into single-ement arrays

### ISSUE THREAD

**Issue by pablo-redradix** [lukeautry/tsoa#1464]
## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Examples for scalar parameters should remain scalar:

```yaml
schema:
  properties:
    stringParam:
      type: string
      example: Lorem ipsum dolor sit amet
    numberParam:
      type: number
      format: double
      example: 4815162342
  required:
  - stringParam
  - numberParam
  type: object
```

## Current Behavior

Instead, they are made into single-element arrays:

```yaml
schema:
  properties:
    stringParam:
      type: string
      example:
      - Lorem ipsum dolor sit amet
    numberParam:
      type: number
      format: double
      example:
      - 4815162342
  required:
  - stringParam
  - numberParam
  type: object
```

## Steps to Reproduce

```ts
  /**
   * @example stringParam "Lorem ipsum dolor sit amet"
   * @example numberParam 4815162342
   */
  @Post('test')
  public async testMethod(
    @BodyProp() stringParam: string,
    @BodyProp() numberParam: number
  ) {
    return
  }
```

## Context (Environment)

Version of the library: Tried with versions 5 and 6-rc
Version of NodeJS: 18.16.1

- Confirm you were using yarn not npm: [X]

**Comment by pablo-redradix** [comment]
I think I found the culprit: in `parameterGenerator.ts` you can find this:

```ts
const { examples: example, exampleLabels } = this.getParameterExample(parameter, parameterName);
```

It merely renames destructured `examples` to `example`, but it's still an array. This does the trick:

```ts
const { examples, exampleLabels } = this.getParameterExample(parameter, parameterName);
const example = examples?.length ? examples[0] : undefined
```

This line can be found five times in said file, once per property type allowing for a single example

**Comment by WoH** [comment]
Shouldn't they have labels, even if they're just called example-{n}? I'd prefer if we used examples for oas 3

**Comment by pablo-redradix** [comment]
Swagger spec doesn't allow for labels in param examples:

```yaml
parameters:
  - in: query
    name: status
    schema:
      type: string
      enum: [approved, pending, closed, new]
      example: approved     #Example of a parameter value
```

Link to [Swagger docs](https://swagger.io/docs/specification/adding-examples/)
