### ISSUE TITLE
Nullable information is lost with Typescript Utility Type (Pick, Partial, ...)

### ISSUE THREAD

**Issue by bigen1925** [lukeautry/tsoa#1515]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
{
    "schemas": {
      "Partial__nullableString-string-or-null__": {
        "properties": {
          "nullableString": {
            "type": "string",
            "nullable": true  #### nullable should be included
          }
        },
        "type": "object",
        "description": "Make all properties in T optional"
      },
      "ReturnType": {
        "$ref": "#/components/schemas/Partial__nullableString-string-or-null__"
      }
    },
}
```

## Current Behavior

```yaml
{
    "schemas": {
      "Partial__nullableString-string-or-null__": {
        "properties": {
          "nullableString": {
            "type": "string"  #### nullable is not included
          }
        },
        "type": "object",
        "description": "Make all properties in T optional"
      },
      "ReturnType": {
        "$ref": "#/components/schemas/Partial__nullableString-string-or-null__"
      }
    },
}
```

## Possible Solution

make nullable information not to be lost

## Steps to Reproduce

1. with Controller
```ts
import { Controller, Get, Route } from "tsoa";

type ReturnType = Partial<{ nullableString: string | null }>;

@Route("sample")
export class SampleController extends Controller {
  @Get()
  getSample(): ReturnType {
    return {} as any;
  }
}
```

2. `npx tsoa spec`

## Context (Environment)

Version of the library: tsoa@6.0.0-rc.5
Version of NodeJS: v18.15.0

- Confirm you were using yarn not npm: [x]

## Detailed Description
Thank you in advance for your development and maintenance for this awesome framework!
I love and use in production this :)

I confirmed that `nullable` is lost when defining types with `Pick` and `Partial` and `Exclude`.

This didn't happen (`nullable` is NOT lost) in `tsoa@5.1.1`.

Please let me know if I can provide any more information.

## Breaking change?

NO
