### ISSUE TITLE
jsdoc @example is used for union type but ignored for enum

### ISSUE THREAD

**Issue by miszczu-drako** [lukeautry/tsoa#1603]
Both union type and enum in typescript are generated to enum in swagger, which is fine and expected.
However if I specify an `@example` in jsdoc for union type, it will be visible in generated swagger file. But it won't be for enum.

## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I expect that `@example` is taken into account both for union type and enum

Source ts file
```ts
/** 
 * the enum type
 * @example "bbb"
 */
enum EnumType {
  AAA = 'aaa',
  BBB = 'bbb'
}

/** 
 * the union type
 * @example "bbb"
 */
type UnionType = 'aaa' | 'bbb';
```

Expected yaml file
```yaml
components:
    schemas:
        EnumType:
            description: 'the enum type'
            enum:
                - aaa
                - bbb
            type: string
            example: bbb
        UnionType:
            type: string
            enum:
                - aaa
                - bbb
            example: bbb
            description: 'the union type'
```

## Current Behavior

Currenlty EnumType is generated without an example

```yaml
components:
    schemas:
        EnumType:
            description: 'the enum type'
            enum:
                - aaa
                - bbb
            type: string
        UnionType:
            type: string
            enum:
                - aaa
                - bbb
            example: bbb
            description: 'the union type'
```

## Steps to Reproduce

1. add `@example` in jsdoc to any enum you have in your code
2. run `tsoa spec`
3. verify that swagger file doesn't contain provided example

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: v20.9.0

- Confirm you were using yarn not npm: [-] (I'm using npm)

## Detailed Description

Nothing to add.

## Breaking change?

No
