### ISSUE TITLE
Bug: date string example gets converted to a yaml date

### ISSUE THREAD

**Issue by weber-software** [lukeautry/tsoa#1769]
Hi there,

i have the following custom type:

```
/**
 * ISO 8601 date string with a fixed format.
 * A date value can be restricted to a range, defined by its answer option.
 *
 * @pattern ^\d{4}-\d{2}-\d{2}$
 * @example "2024-02-06"
 */
export type IsoDateString = string;
```

And when running `tsoa spec` with @tsoa/cli @6.1.0 i get what i would expect:

```
        IsoDateString:
            type: string
            example: '2024-02-06'
            description: "ISO 8601 date string with a fixed format.\nA date value can be restricted to a range, defined by its answer option."
            pattern: '^\d{4}-\d{2}-\d{2}$'
```

When using @tsoa/cli @6.2.0 or @6.6.0 i get the following:

```
    IsoDateString:
      type: string
      example: 2024-02-06
      description: |-
        ISO 8601 date string with a fixed format.
        A date value can be restricted to a range, defined by its answer option.
      pattern: ^\d{4}-\d{2}-\d{2}$
```

Please note that the `example` has no quotes and is therefore a date and not a string as i would expect.
