### ISSUE TITLE
Single literal type does not work correctly

### ISSUE THREAD

**Issue by mattchr** [lukeautry/tsoa#320]
```
interface WorksCorrectly {
  myLiteral: 'hello' | 'world';
}

interface DoesNotWork {
  myLiteral: 'hello';
}
```

I believe that this should produce an enum that allows a single item.

A workaround is to declare it as a typescript enum, or a string literal with two redundant values
```
enum SingleValueEnum {
  HELLO = 'hello',
}

interface WorkAround {
  myLiteral: SingleValueEnum;
}

interface WorkAroundUglier {
  myLiteral: 'hello' | 'hello';
}
```

**Comment by dgreene1** [comment]
New maintainer here. Sorry for the delay. I'd like to confirm your expectations. So you'd like to see something like be produced right?

```yaml
definitions:
  ObjectWithOneValue:
    type: object
    properties:
      myLiteral:
        type: string
        enum:
          - hello
  ObjectWithTwoValues:
    type: object
    properties:
      myLiteral:
        type: string
        enum:
          - hello
          - world
```

And that's if you provided:
```ts
interface ObjectWithTwoValues {
  myLiteral: 'hello' | 'world';
}

interface ObjectWithOneValue {
  myLiteral: 'hello';
}
```
