### ISSUE TITLE
Add argument to Parameter Decorators

### ISSUE THREAD

**Issue by WoH** [lukeautry/tsoa#489]
# Proposal: Add argument to Parameter Decorators

Affected Decorators:
- Query
- Path
- Header

## Current Behavior

Parameter Decorators can't be used to specify parameter details.

## Expected behavior:

```ts
  @Get()
  public async getModel(
    @Query({
      description: 'This is a description for my query parameter',
      examples: [{
        name: 'trueExample',
        value: true
      }, {
        name: 'falseExample',
        value: false
      }]
    }) stringQueryParam: string
  ): Promise<TestModel> {
```

produces:

```yaml
      parameters:
        - description: This is a description for my query parameter
          in: query
          name: stringQueryParam
          required: true
          examples:
            trueExample:
              value: true
            falseExample:
              value: false
```

## Possible Solution

Parameter Decorators should have an optional argument of type

```ts
interface ParameterConfig {
  description?: string,
  required?: boolean,
  deprecated?: boolean,
  example?: unknown,
  examples?: ExampleObject[] //OpenAPI 3 only, should warn for swagger
}

interface ExampleObject {
  name: string,
  summary?: string,
  description?	string,
  value?: unknown,
  externalValue?: string
}
```

## Breaking change?
No, since the config object should be optional.

## Notes:
tsoa provides a helper to get the decorator argument, anyone interested in implementing may wanna look at [that](https://github.com/lukeautry/tsoa/blob/master/src/utils/decoratorUtils.ts#L44) to get an idea on how to get the decorator argument in order to merge it with the metadata for parameters [here](https://github.com/lukeautry/tsoa/blob/master/src/metadataGeneration/parameterGenerator.ts).

This metadata is subsequently used to generate the [swagger](https://github.com/lukeautry/tsoa/blob/master/src/swagger/specGenerator2.ts#L210)/[openapi](https://github.com/lukeautry/tsoa/blob/master/src/swagger/specGenerator3.ts#L246) specification.

## Alternative approaches:

There's an approach that would take care of the description [here](https://github.com/lukeautry/tsoa/issues/85), but I think this approach covers more use-cases.
If someone thinks there is an argument to move all of this into jsDoc, I'd enjoy seeing a different proposal aswell.

I've seen some implementations of this issue so I thought I'd write down more info for everyone to get a better idea. Maybe this should be a good first issue / help wanted.
