### ISSUE TITLE
Numeric enums are being documented as string enums

### ISSUE THREAD

**Issue by dgreene1** [lukeautry/tsoa#492]
The numeric enum PR (https://github.com/lukeautry/tsoa/issues/331) didn't have the correct type showing in Swagger.

## Sorting

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
paths:
  /items:
    get:
      parameters:
        - in: query
          name: someNumber
          description: a number that I want the user to provide
          schema:
            type: number
            enum: [1, 2]
```

```ts
export enum someNumber {
  one = 1,
  two = 2
}
```

## Current Behavior

The `schema.type` parameter is wrong.
```yaml
paths:
  /items:
    get:
      parameters:
        - in: query
          name: someNumber
          description: a number that I want the user to provide
          schema:
            type: string
            enum: [1, 2]
```

```ts

```

## Possible Solution

Have the code check if the enum only has one type or the other and then use that type.

## Steps to Reproduce

1. Use the enum provided above and see what it outputs

## Context (Environment)
Version of the library: v2.5.4
Version of NodeJS: LTS
* Confirm you were using yarn not npm: [X]

## Breaking change?
no
