### ISSUE TITLE
Enums with strings and numbers should not be supported

### ISSUE THREAD

**Issue by dgreene1** [lukeautry/tsoa#501]
The goal is to be more strict in v3 so we can clarify to users why they're getting a bad swagger document when they used mixed enums (i.e. enums with strings and numbers).

See this comment for more information: https://github.com/lukeautry/tsoa/pull/493/files#r330696346

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

in the v2 branch, if you pass in an enum with strings and numbers then it tries to build a swagger object, but it shouldn't
```ts
export enum MixedStringAndNumberEnum {
  one = 1,
  two = 'two',
  three = 3,
  four = 'four',
}
```
Due to requirements to not create breaking changes within v2, we had no choice but to build some schema, but it's wrong:
```yaml
paths:
  /items:
    get:
      parameters:
        - in: query
          name: sort
          description: Sort order
          schema:
            type: string // <-- If swagger were to support it, this should be string | number
            enum: [1, two, 3, four]
```
Ideally it would throw an error.

## Possible Solution

* Throw an error that clarifies that swagger/ OpenAPI does not support enums with strings and numbers

## Steps to Reproduce

1. see the unit test labeled `"should warn if an enum is mixed with numbers and strings"`
2. that ^ is the unit test that should be changed to be `"should throw an error if an enum is mixed with numbers and strings"`

## Breaking change?

yes, that's why I'm adding it the the `V3` github project kanban board
