### ISSUE TITLE
Better handling for `true` or `false` literals in unions

### ISSUE THREAD

**Issue by dgreene1** [lukeautry/tsoa#510]
## Sorting

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
```ts
export type ComplicatedLiteralUnion = "hello" | false;
```

I would expect to get OpenAPI schema like:
```yaml
      oneOf:
        - type: string
          enum:
            - hello
        - type: boolean
          enum:
            - false
```

## Current Behavior
In the 2.0 branch it pretends that the boolean is a string
```yaml
      oneOf:
        - type: string
          enum:
            - hello
            - false
```

## Possible Solution
Have the code produce the expected result above.

## Steps to Reproduce
1. Create a tsoa route that returns this object (note: in the 2.0 branch you can't use an exported type so it has to be inline)
```ts
export interface ObjectThatHasComplicatedLiteral {
  complicatedLiteral: 'hello' | false
}
```

## Context (Environment)
Version of the library: 2.5.5
Version of NodeJS: LTS
* Confirm you were using yarn not npm: [X]

## Breaking change?
Yes, so I've put it in the 3.0 project

**Comment by dgreene1** [comment]
Btw, the reason why I think that it should be two separate enums is due to this explanation in JSON Schema:
```
However, in most cases, the elements in the enum array should also be valid against the enclosing schema:

{
  "type": "string",
  "enum": ["red", "amber", "green", null]
}
This is in the enum, but it’s invalid against { "type": "string" }, so it’s ultimately invalid:
```
And yes, I recognize that OpenAPI is not JSONSchema, but it's a great example of the principle that the values in the enum must satisfy the type of the enum.

Read more here: https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values

**Comment by WoH** [comment]
My plan is to produce a type aware enum for each literal type and treat that like any other union for the next major.

**Comment by dgreene1** [comment]
Cool, then you can use this issue number to track that.

**Comment by dgreene1** [comment]
And more importantly, now you have acceptance criteria. Because neither of the following should happen:

```yaml
      oneOf:
        - type: string
          enum:
            - "hello"
            - false
```

```yaml
      oneOf:
        - type: string
          enum:
            - "hello"
            - "false"
```
