### ISSUE TITLE
@Query() Can't support array 'refAlias' type

### ISSUE THREAD

**Issue by Ze-Khan** [lukeautry/tsoa#561]
Previously in v2.5.x tsoa was able to support string literal type arrays in the query parameter. However v3 is showing breaking changes on this behavior.

## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yml
"/route":
  post:
    parameters:
    - in: query
      name: mode
      required: false
      schema:
        default:
        - 1
        - 2
        - 3
        type: array
        items:
          type: string
          enum:
          - 1
          - 2
          - 3
      collectionFormat: multi
```

## Current Behavior

Error: @Query('mode') Can't support array 'refAlias' type.

## Steps to Reproduce

```ts
type Mode = '1' | '2' | '3';
@Query() mode: Mode[] = ['1', '2', '3'];
```

## Context (Environment)
Version of the library: v3.0.0
Version of NodeJS: v10.16.3

## Breaking change?
v3 breaking changes
