### ISSUE TITLE
Aliased void Api Response types use 200 response instead of 204

### ISSUE THREAD

**Issue by fantapop** [lukeautry/tsoa#603]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
     "/assets/v1/{id}": {
      "delete": {
        "operationId": "deleteAsset",
        "responses": {
          "204": {
            "content": {
              "application/json": {}
            },
            "description": "No content"
          },
```

```ts

    type AssetDeleteResponseType = void;

    public async delete(
        id: string,
        @Request() request: express.Request,
    ): Promise<AssetDeleteResponse> 
```

## Current Behavior

```yaml
{
  "components": {
    "examples": {},
    "headers": {},
    "parameters": {},
    "requestBodies": {},
    "responses": {},
    "schemas": {
      "AssetDeleteResponse": {},
    },
    "paths": {
     "/assets/v1/{id}": {
      "delete": {
        "operationId": "deleteAsset",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AssetDeleteResponse"
                }
              }
            },
            "description": "Ok"
          },
```

```ts
    public async delete(
        id: string,
        @Request() request: express.Request,
    ): Promise<void> {
```

## Possible Solution
It seems like the only solution to this would be to detect that the type resolves to void and change the open api spec to have the response under 204.  This means that the type alias doesn't carry over to any remote clients however at least its accurate.

### Workaround
Use void directly in api responses that return void.  This isn't a bad workaround but I lost some time to the unexpected behavior so I decided to go ahead and file it.

## Context (Environment)
Version of the library: 3.0.2
Version of NodeJS: 12.12.0
* Confirm you were using yarn not npm: [x]
