### ISSUE TITLE
feature: class methods and getter

### ISSUE THREAD

**Issue by Eywek** [lukeautry/tsoa#631]
I'm using tsoa with a typegoose model and I have some virtuals fields with getter and some methods used in backend. 
I want to be able to display my virtuals in my swagger definitions and ignore my methods without adding any jsdoc comment to ignore it.

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
        Datasource:
            properties:
                name:
                    type: string
                pausedAt:
                    type: string
                    format: date-time
                isPaused:
                    type: boolean
            required:
                - name
                - pausedAt
            type: object
```

```ts
export class Datasource {

  @prop({
    trim: true,
    required: [true, 'NameEmpty']
  })
  public name!: string

  @prop({
    default: () => null
  })
  public pausedAt!: Date | null

  public get isPaused () {
    return this.pausedAt !== null
  }
}
```

## Current Behavior

An error occur with the getter or the method without an ignore jsdoc comment.
