### ISSUE TITLE
Support multiple examples

### ISSUE THREAD

**Issue by fantapop** [lukeautry/tsoa#650]
It looks like open api 3 supports multiple examples.  It would be great to support this.

https://swagger.io/docs/specification/adding-examples/

## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
"Location": {
    "examples": [
      {
        "code": "98104",
        "country": "US",
        "province": "WA",
        "locality": "Seattle"
      },
      {
         "code": "BR12AA",
         "country": "GB",
         "province": "London"
      },
      {
          "country": "NL"
      }
    ]
}
```

```ts
/**
 * @example {
 *   "code": "98104",
 *   "country": "US",
 *   "province": "WA",
 *   "locality": "Seattle"
 * }
 *
 * @example {
 *   "code": "BR12AA",
 *   "country": "GB",
 *   "province": "London"
 * }
 *
 * @example {
 *   "country": "NL"
 * }
 */
export interface Location {
```

## Current Behavior
Currently only one example shows up

## Context (Environment)
Version of the library: 3.0.4
Version of NodeJS: 12.12.0
* Confirm you were using yarn not npm: [x]

## Detailed Description
If multiple example decorators are found, render an examples array in the swagger document instead of example.

## Breaking change?
No
