### ISSUE TITLE
Support for multiple servers information

### ISSUE THREAD

**Issue by deividfortuna** [lukeautry/tsoa#720]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
```

## Current Behavior

```yaml
servers:
  - url: https://api.example.com/v1 
```

## Possible Solution
```ts
  private buildServers() {
    if (Array.isArray(this.config.host)) {
      return this.config.host.map(host => this.buildServer(host));
    } else {
      return [this.buildServer({ host: this.config.host })];
    }
  }

  private buildServer(serverConfig: { host?: string; description?: string }): Swagger.Server {
    const basePath = normalisePath(this.config.basePath as string, '/', undefined, false);
    const scheme = this.config.schemes ? this.config.schemes[0] : 'https';
    const url = serverConfig.host ? `${scheme}://${serverConfig.host}${basePath}` : basePath;

    const server = {
      url,
    } as Swagger.Server;

    if (serverConfig.description) {
      server.description = serverConfig.description;
    }

    return server;
  }
```

## Context (Environment)

Version of the library: 3.0.8
Version of NodeJS: v12.16.3

- Confirm you were using yarn not npm: [x]

## Detailed Description

OpenApi3 supports multiples servers information and that can be useful to be used swagger pointing to multiple environments.

## Breaking change?
The solution is a workaround to a breaking change.
