### ISSUE TITLE
@Extension won't work if second argument is a function 

### ISSUE THREAD

**Issue by UnlimitedX** [lukeautry/tsoa#771]
Hi everyone,
I am using Amazon API Gateway in a project so I need to manage the x-amazon-apigateway-integration variable with our swagger file. 

Everything works well if I use a JSON string as the second argument of the _@ Extension_ decorator, anyway, since the whole JSON is a few lines long I don't want to repeat it on each route. That would make the controllers very redundant.

So I am using a static function to generate this JSON for the _@ Extension_, used as the second parameter. 

BUT With this method, the x-amazon-apigateway-integration isn't generated anymore in the swagger file. 

## Sorting

- **I'm submitting a ...**

  - [X] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

The variable should be in the Swagger.json even if I use my static function:

```yaml
"x-amazon-apigateway-integration": {
    "uri": "https://api.XXXXXX.net/datatypes/",
    responses": {
        "default": {
            "statusCode": "200"
        }
    },
    "passthroughBehavior": "when_no_match",
    "httpMethod": "GET",
    "type": "http"
}
```

```ts
@Extension("x-amazon-apigateway-integration", AmazonTSOAExtension.generate("datatypes/", "200", "GET", "http"))
```
And my function:

```ts
import { ExtensionType } from "tsoa";

export class AmazonTSOAExtension {
    static generate(route: string, responseStatusCode: string, method: string, protocol: string): ExtensionType {
        return {
            "uri": "https://api.XXXXXX.net/" + route,
            "responses": {
                "default": {
                    "statusCode": responseStatusCode
                }
            },
            "passthroughBehavior": "when_no_match",
            "httpMethod": method,
            "type": protocol
        }
    }
}
```

## Current Behavior

The x-amazon-apigateway-integration doesn't appear in the generated swagger.json if I use a function to generate the value.

## Possible Solution

We should be able to use a function to generate the _@ Extension_ content.

## Context (Environment)

Version of the library: 3.2.1
Version of NodeJS: 13.11.0

- Confirm you were using yarn not npm: [ ]
**USING NPM**, generating the swagger file with `tsoa spec`
