### ISSUE TITLE
Type names from typescript type alias definitions

### ISSUE THREAD

**Issue by filiplindqvist-netlight** [lukeautry/tsoa#798]
**To start off: great library 😍  !!!**

Question/issue about the naming of Schemas. 

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```ts
type LoginStatus = {
    loggedIn: boolean;
    username: string;
}

/**
 * A narrower LoginStatus
 */
type LoginStatusFailed = Pick<LoginStatus, 'loggedIn'>

@Route('api/v1/login')
export class LoginController extends Controller {

    @Path('/')
    @Post()
    @Response<LoginStatusFailed>(StatusCode.UNAUTHORIZED, "Unauthorized", { loggedIn: false })
    public async doLogin(...): Promise<LoginStatus> {
       this.setStatus(StatusCode.UNAUTHORIZED)
       return { loggedIn: false }
    }
}

```

## Current Behavior

Expecting **LoginStatusFailed** instead of `Pick_LoginStatus.loggedIn_`.

**Swagger UI**
![image](https://user-images.githubusercontent.com/71712056/94368093-ae312f80-00e2-11eb-8062-5c38fe7b00a5.png)

**Spec Schemas**
```yaml
"LoginStatus": {
    "properties": {
        "username": {
            "type": "string"
        },
        "loggedIn": {
            "type": "boolean"
        }
    },
    "required": [
        "loggedIn", "username"
    ],
    "type": "object"
},
"Pick_LoginStatus.loggedIn_": {
    "properties": {
        "loggedIn": {
            "type": "boolean"
        }
    },
    "required": [
        "loggedIn"
    ],
    "type": "object",
    "description": "From T, pick a set of properties whose keys are in the union K"
},
"LoginStatusFailed": {
    "$ref": "#/components/schemas/Pick_LoginStatus.loggedIn_",
    "description": "A narrower LoginStatus"
},
...
```

**DoLogin controller**
This seems to be correct in swagger.json `paths["/api/v1/login"].post.responses["401"].content["application/json"].schema.$ref`. 

```yaml
"schema": {
    "$ref": "#/components/schemas/LoginStatusFailed"
},
```

## Steps to Reproduce

1. Create type alias using Omit or Pick
2. Make Controller method return type alias
3. Expect type alias name to be the schema name

## Context (Environment)

Version of the library: 3.3.0
Version of NodeJS: v12.18.3

Also using "swagger-ui-express" 4.1.4 to display spec. 

## Detailed Description

Would also be nice if `From T, pick a set of properties whose keys are in the union K` could be rendered with the proper types, not sure if achievable.
