### ISSUE TITLE
basePath is being set incorrectly

### ISSUE THREAD

**Issue by BradenCTC** [lukeautry/tsoa#818]
## Sorting

- **I'm submitting a ...**

  - [x ] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [ x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
servers:
    -
        url: 'http://xx.xxx.x.x/product'
```

## Current Behavior

```yaml

servers:
    -
        url: '/http:/xx.xxx.x.x/product'
```

## Possible Solution

Remove the prepended '/' before 'http' and do not remove the second '/' after 'http:'

## Steps to Reproduce

1. Set the basePath property in tsoa.json as follows and run tsoa:
"spec": {
        "basePath": "http:////xx.xxx.x.x/product",
        "outputDirectory": "src/swagger",
        "specVersion": 3,
        "yaml": true
    },

## Context (Environment)

Version of the library: ^3.3.0
Version of NodeJS: 12.16.3

- Confirm you were using yarn not npm: [npm]

## Detailed Description

The server url is being formatted incorrectly to /http:/xx.xxx.x.x/product instead of 'http://xx.xxx.x.x/product'. Remove the prepended '/' before 'http' and do not remove the second '/' after 'http:'.
