### ISSUE TITLE
bug: conditional mapped type

### ISSUE THREAD

**Issue by Eywek** [lukeautry/tsoa#823]
Hello (I'm back), when we use conditional mapped types with tsoa, original values are written in the spec instead of updated one.

I'm working on a pull-request to fix it.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
Serialize__bar-foo.foo-string__:
        properties:
            bar:
                type: string
                enum:
                    - bar
                x-nullable: false
            foo:
                type: string
        required:
            - bar
            - foo
        type: object
```

```ts
type Serialize<T extends any> = {
  [key in keyof T]: T[key] extends 'foo' ? 'bar' :
                    T[key]
}

Serialize<{ bar: 'foo', foo: string }>;
```

## Current Behavior

```yaml
Serialize__bar-foo.foo-string__:
        properties:
            bar:
                type: string
                enum:
                    - foo
                x-nullable: false
            foo:
                type: string
        required:
            - bar
            - foo
        type: object
```

## Context (Environment)

Version of the library: v3.4.0
Version of NodeJS: v14.5.0

- Confirm you were using yarn not npm: [x]
