### ISSUE TITLE
DRY validations?

### ISSUE THREAD

**Issue by gaggle** [lukeautry/tsoa#837]
Can validation specifications be reused across multiple endpoints without copy-pasted jsdoc specifications?

## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

```yaml
				"parameters": [
					{
						"in": "query",
						"name": "limit",
						"required": true,
						"schema": {
							"format": "int32",
							"type": "integer",
							"minimum": 0
						}
					}
				]
```

I think I was expecting to be able to write something like this:
```ts
  @Get("foo")
  public async foo (@Query() @integerValidation({minimum: 0}) limit: number): Promise<any> {
```
(that is: the validation here is code-based, not jsdoc based, allowing to to be extracted into a write-once-use-in-many-endpoints variable)

## Current Behavior

```ts
  /**
   * @param {number} limit
   * @isInt limit must be integer
   * @minimum limit 0 minimum 0
   */
  @Get("foo")
  public async foo (@Query() limit: number): Promise<any> {
```

## Context (Environment)

Version of the library: 3.3.0
Version of NodeJS: 10.22.0

- Confirm you were using yarn not npm: [ ]

## Detailed Description

As far as I can tell we must specify query validations using jsdoc strings. That works great, but it leads to multiple endpoints having to re-specify their validation settings over and over. I wanted to ask if it's possible to DRY those out, to specify a pagination query parameter once and use it in multiple endpoints?

And thanks for making tsoa available, it's a lovely library.
