### ISSUE TITLE
How to gen swagger.json for request body description?

### ISSUE THREAD

**Issue by steven130169** [lukeautry/tsoa#933]
## How to gen swagger.json for request body description?

- **I'm submitting a ...**

  - [ ] support request

- I confirm that I
  - [ ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

First , I use a interface to gen a swagger request body example.
like this.
```ts
/**
*
* @example {
*  "a" : 1
*  "b" : 2
* }
* @description a    first number
* @description b    second number
*/
interface testModel{
 a : number,
 b : number
}
```

Second,  My Controller like this
```ts
    @Post('integer')
    public async postInteger(
        @Body() numberBody: testModel): Promise<any> {
          return numberBody.a + numberBody.b;
    }

```
The end , I want to get a swagger file like this

```yaml
      properties:
        a:
          type: number
          description:   first number
        b:
          type: number
          description:   second number
```

## Current Behavior

swagger.json not have any "description" key

## Possible Solution

I have no other idea  to gen "description"

## Detailed Description

tsoa can do that ?
