### ISSUE TITLE
@UploadedFile should add a required to spec non-optional?

### ISSUE THREAD

**Issue by qqilihq** [lukeautry/tsoa#942]
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Happy to see the @UploadedFile functionality (see https://github.com/lukeautry/tsoa/pull/920).  

I think that the generated `swagger.json spec` should contain e.g. a `required": ["file"]` if the property is non-optional like e.g. here 

```ts
async uploadFile(@UploadedFile() file: Express.Multer.File): Promise<IFile> {
```

I would expect:

```yaml
    "/file/upload": {
      "post": {
        "operationId": "UploadFile",
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IFile"
                }
              }
            }
          }
        },
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                },
                "required": ["file"]
              }
            }
          }
        }
      }
    },
```

## Current Behavior

The spec currently looks like:

```yaml
    "/file/upload": {
      "post": {
        "operationId": "UploadFile",
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IFile"
                }
              }
            }
          }
        },
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        }
      }
    },
```

## Context (Environment)

Version of the library: 3.6.0

- Confirm you were using yarn not npm: [x]

## Detailed Description

* Add `required` attribute for non-optional `@UploadedFile` params in the generated spec.
